#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'
require 'psych'

gloable_folder = '~/Dropbox'
task_file_name = 'tasks.yml'

program :name, 'Forget Me Not'
program :version, '0.0.1'
program :description, 'A smart, contextualized todo list. Designed to live in your terminal, and to be in your face.'

command :list do |c|
  c.syntax = 'fmn list, [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |args, options|
    current_dir = Dir.pwd
    dirs = [current_dir]
    while File.expand_path('..', current_dir) != current_dir do
      dir = File.expand_path('..', current_dir)
      dirs.push dir
      current_dir = dir
    end

    tasks = []
    dirs.each do |dir|
      path = "#{dir}/#{task_file_name}"
      if File.exists?(path) then
        yaml = Psych.load_file(path)
        tasks.push(yaml["tasks"])
      end
    end

    tasks = tasks.flatten

    tasks.each do |t|
      puts "- #{t}"
    end
  end
end

command :add do |c|
  c.syntax = 'fmn add, [options]'
  c.summary = 'Add a task to the forget me not list.'
  c.description = 'Add a task to the forget me not list.'
  c.example 'Add a task to the forget me not list. You don\'t need quotes.', 'fmn add Buy the milk'
  c.option '-g', '--global', 'Add to the global list'
  c.action do |args, options|
    task = args.join(' ')
    if options.global
      say 'Will add task to global list'
    else
      say 'Will add task to local list'
    end
  end
end

command :done do |c|
  c.syntax = 'fmn done [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |args, options|
    say 'Delete feature not implemented yet'
  end
end

